spring:
  application:
    name: OnlinePlacementManagement
  datasource:
    url: jdbc:mysql://localhost:3306/placement_management?createDatabaseIfNotExist=true
    username: { yourUsername }
    password: { yourPassword }
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 9321


